# Generated by Django 6.0.7 on 2026-07-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='team',
            name='gender',
            field=models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls')], default='BOYS', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('sport', 'name', 'team_type', 'gender')},
        ),
    ]
