# Generated by Django 6.0.7 on 2026-07-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_venue_session_schedule_slot_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='gender',
            field=models.CharField(choices=[('BOYS', 'Male'), ('GIRLS', 'Female')], default='BOYS', max_length=10),
        ),
    ]
