# Generated by Django 6.0.7 on 2026-08-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_school_userprofile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='full_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_status_note',
            field=models.TextField(blank=True),
        ),
    ]
